### PR TITLE
#486 prevent sending Signup Command if no identity providers

### PR DESCRIPTION
**Pull request by maxim-s**

### CODE REVIEW

**Comment by maxim-s** [comment]
looks like need to rerun  coverage/coveralls after PR synchronization , because when I added test still have the same coverage

**Comment by AndersAbel** [comment]
The coverage is automatically recalculated after a rebuild. The [coveralls page](https://coveralls.io/github/KentorIT/authservices) shows that there's been two builds from your PR.

The non-covered condition in the if-statement is complex, so probably not all of those conditions are properly covered any more. Are they even needed? Might be that some of those null checks can be removed. Can Options.IdentityProviders really be null? If it can, there must be a test case that covers it.

**Comment by maxim-s** [comment]
@AndersAbel yes sure,thank you, it's impossible to have null for IdentityProviders property

**Comment by AndersAbel** [comment]
What about behaviour when AuthServices is explicitly stated in the AuthenticationTypes in the challenge? There are three cases. The wildcard case only makes sense when the middleware is set as active, but the reasoning should be the same.

* No AuthenticationTypes specified => Don't call SignInCommand if there is no Idp.
* One AuthenticationType specified and it matches Options.AuthenticationType => I prefer an exception to be thrown if there is no Idp. Otherwise it will just become a very strange error.
* Multiple AuthenticationTypes specified and one matches Options.AuthenticationType => Advanced scenario that indicates that the user knows what's going on. Don't call SignInCommand to let other middlewares have a chance.

What do you think about those alternatives?

**Comment by maxim-s** [comment]
yes, reasonable cases, just want to check it in current environment

**Comment by AndersAbel** [comment]
Closing due to no updates after my comments 1st of June. Please comment to reopen if you want to carry this forward.

**Pull request closed without merging**
