### PR TITLE
Issuer extraction fixed

### PR DESCRIPTION
**Pull request by FeiWongReed**
Fix for #477

### CODE REVIEW

**Comment by explunit** [comment]
Does the standard say that the first assertion is authoritative for issuer if it's not found in the top-level response tag? We may want to be cautious about this, given the signature-wrapping attacks. It would seem that if we adopt your suggested fix that the signature checking logic would need to change to lookup issuer on every assertion rather than using this top-level issuer property to find the Ipd & its keys.

Also, on PR logistics, some things to note:
 * You'll need some unit tests to fix the code coverage failure you see above
 * You should do the PR from a branch in your repo rather than master. 
See https://github.com/KentorIT/authservices/blob/master/CONTRIBUTING.md

**Comment by AndersAbel** [comment]
@explunit is right about the signature processing being affected. This is what the WebSSO Profile section 4.1.4.2 says:

> If the <Response> message is signed or if an enclosed assertion is encrypted, then the <Issuer> element MUST be present. Otherwise it MAY be omitted.

So if there is no Issuer on the Response, the `Saml2Response.Issuer` property should be left as null. The signature validation code need to be adjusted accordingly so that any signed assertions are validated against the key of the `issuer` of the assertion. I think that there are cases with proxying where an idp might send a response containing assertions issues by another idp.

**Comment by AndersAbel** [comment]
Closing due to inactivity. If you're still working on this, please leave a comment and I'll reopen.

**Comment by FeiWongReed** [comment]
I've reported a bug and proposed quick fix. Ok, code-style-coverage-and-so-on make my fix unacceptable, but I have no time to do everything in perfect way, I'm sorry. Maybe later, not today.

**Comment by AndersAbel** [comment]
I understand if you don't have time to work further on it, but quick fixes that do not stand up to the quality standards of the library will not be accepted. In this case it was not only test coverage that lacked but also logic around the signature validation. That is a **very** sensitive part of the code and changes must be very well worked through to be accepted.

**Pull request closed without merging**
