### PR TITLE
Add single logout support

### PR DESCRIPTION
**Pull request by cederlof**
Addressing issue #29.
I used some of the code from pull request [#197](https://github.com/KentorIT/authservices/pull/197).

Todo: 
* Add logout-functionality to the StubIdp
* Sign the logout request and validate response with certificate

AuthServicesController.cs/Signout()-method is used for triggering this logout. I'm uncertain if that is the right way to go, or perhaps make a separate method for doing the SingleLogout-call, as this changes the existing behaviour of that method.

To configure the logout-url for the Idp, modify your web.config to add attribute `singleLogoutUrl` in kentor.authServices/identityProviders/add.

### CODE REVIEW

**Comment by cederlof** [comment]
Any status on this pull-request?

**Comment by AndersAbel** [comment]
I have looked briefly at this, and there is some work to do before merging:

* There are no tests for the Single Logout Functionality. 100% unit test coverage is required.
* There are build issues in the current branch. Looks like the source file name doesn't match the name referenced in the csproj.

For the feature to be complete, there is even more work do to, but that can be done in a separate pull request from someone else.
* An Owin implementation
* The SessionNotOnOrAfter value in the received response should be respected.
* The SessionId from the Idp should be preserved.
* A single logout endpoint should be exposed in metadata.
* There should be support for handling a single logout initiated by another SP. That means receiving a single logout request from the idp, signing out the current user and redirecting back to the idp.

I have a commitment to deliver working single logout to a customer before the end of the year, so I'm planning to pick up this PR and make the required work to get it merged (unless someone else gets things done first).

**Comment by cederlof** [comment]
Thanks for your prompt reply @AndersAbel ! I might get time to do some of those things. If so, I'll keep this pull request updated.

**Comment by birchoff** [comment]
Just curious when you say that you have a commitment to "deliver single logout to a customer before the end of the year" do you have a better idea of the deadline. I ask because I also need to have working Single Sign out for my client and I have been procrastinating on forking and integrating this particular pull request because I suspected it would be merged, and I don't know enough about the code base to be confident that everything still works the way its supposed to.

That said If you are still a month away from getting all these changes implemented I wouldn't mind pitching in if you could point me to some documentation that could help me get up to speed quickly.

**Comment by radharbt** [comment]
Service Provider initiated single logout is working fine. But Idp initiated single logout is not working. Its logging out only the Idp not service providers. Anything we have to change for this?

**Comment by cederlof** [comment]
@radharbt See the last item in Anders' post. It is not yet implemented.

*There should be support for handling a single logout initiated by another SP. That means receiving a single logout request from the idp, signing out the current user and redirecting back to the idp.*

**Comment by snobles** [comment]
Do you think there is any chance of merging the code that handles the SP-initiated logout and handling the Idp-initiated logout separately? I think even Shibboleth didn't support Idp-initiated logout until the most recent version, but handled SP-initiated for some time. Sure, I'm just like all of the other people who are using the fine work done by @cederlof in the meantime, and I know it seems a bit like whining, but I wonder if they really do *have* to be delivered together.

**Comment by AndersAbel** [comment]
@snobles I would be fine with merging this as an intermediate if the first two issues are fixed (add tests and fixing the build issue).

**Comment by AndersAbel** [comment]
@birchoff Time is flying and customer priorities change. I no longer think that I'll make it on this side of New Year. For a discussion on the implementation, please see #29.

**Comment by snobles** [comment]
@AndersAbel I looked back at what I had to do to get it working for several different providers (prototype-level). It seems like you covered most of this in the other thread comment. So I'm not sure if this helps, but I had to:

* Ensure the Single Logout URL is mapped from metadata or can be manually configured (because some providers like OneLogin support a Single Logout endpoint but do not add it to the metadata document).
* Support an OWIN implementation
* Sign the logout request (Okta, for example, requires it to be signed)
* Handle LogoutResponse elements in the deserialized IdP response

**Comment by radharbt** [comment]
I am having two service provider say SP1 and SP2. while logout from SP1 its logging out only idp and SP1. Likewise while logout from SP2 its logging out only idp and SP2. Instead of logout from idp, SP1 and SP2. Did I miss anything?

**Comment by AndersAbel** [comment]
@radharbt If you hit logout on SP1, it will be SP-initiated logout for SP1, but SP2 receives it as Idp-initiated logout which is not supported yet. It is planned for a release in late January.

**Comment by cederlof** [comment]
@AndersAbel I added a few tests and fixed the merge-issue. However, AppVeyor seems to have trouble building, which I can't reproduce locally. I'm building in Visual Studio 2015, but that shouldn't be an issue?

**Comment by AndersAbel** [comment]
The appveyor builds are still experimental. It's a config error from my side that it did build the PR. I'll look into the tests later, trying to have some vacation with the family for a few days now.

**Comment by iRonJ** [comment]
I compiled this branch as-is to use in a Forms-based app, and I continuously get this error:
>[NullReferenceException: Object reference not set to an instance of an object.]
   Kentor.AuthServices.HttpModule.HttpRequestBaseExtensions.ToHttpRequestData(HttpRequestBase requestBase) +509
   Kentor.AuthServices.HttpModule.Saml2AuthenticationModule.OnBeginRequest(Object sender, EventArgs e) +654

**Comment by AndersAbel** [comment]
@iRonJ I (finally) have some planned time to look into this and get Single Logout into the main branch. I will probably start working on it during next week. If you want to help, you're more than welcome to do so. Further up in the conversation is a list from me on what I see as remaining. Also check out the additional things @snobles mentioned.

**Comment by iRonJ** [comment]
I've got a mostly-working version of singlesignout on Feide at this point, based on this code. I did notice however that trying to bind to this IdP: idp.testshib.org AuthServices does not like the metadata there. I haven't dug into that too deeply, just putting this out there. I hope to merge my additions with cederlof's soon though.

**Comment by rajsekharr83** [comment]
`@radharbt If you hit logout on SP1, it will be SP-initiated logout for SP1, but SP2 receives it as Idp-initiated logout which is not supported yet. It is planned for a release in late January.`

This is the comment posted on last December. Do we support  Idp-initiated logout now?
I have the same issue,  What should done to make it working ?

**Pull request closed without merging**
