### PR TITLE
158 appveyor

### PR DESCRIPTION
**Pull request by albinsunnanbo**
A bunch of fixes for running Kentor.AuthServices on AppVeyor for #158
 - Set up NuGet package restore on solution
 - Configure git for CRLF endings
 - Specify test assembly to not run VSPremium tests
 - Note about setting up AppVeyor for contributors

An AppVeyor project of my personal fork building this branch is available on https://ci.appveyor.com/project/albinsunnanbo/authservices

### CODE REVIEW

**Comment by albinsunnanbo** [comment]
Managed to configure a before_build nuget restore script in appveyor.yml.
However after a rebase there are a bunch of tests failing.
https://ci.appveyor.com/project/albinsunnanbo/authservices/build/1.0.17/tests

Most likely this is due to Appveyor blocking the metadata server somehow

**Comment by albinsunnanbo** [comment]
Actually when applying #178 the fail message is `Assert.Fail failed. Timeout passed without condition becoming false, expected 1/10/2015 4:29:36 PM, last actual value was 1/10/2015 4:29:36 PM`
The time is not `DateTime.MinValue` that would be the expected value if metadata load had failed.
Then there is something else :-(

**Comment by albinsunnanbo** [comment]
Increasing timeout in SpinWait from 0,5 to to 2 seconds solved most of the issues

**Comment by AndersAbel** [comment]
Merged in 0aff7bd

**Pull request closed without merging**
