### PR TITLE
Oktadoc

### PR DESCRIPTION
**Pull request by dahlsailrunner**
Based on Albin Sunnanbo's request from issue #304, I have added some documentation regarding what I did to get Okta configured as an identity provider within my IdentityServer3 project.  I added a new doc to the doc folder, an image to same with a screenshot of config options, and updated the main readme to ref the new doc.

### CODE REVIEW

**Comment by albinsunnanbo** [comment]
Hi, thanks for the effort!
It looks good and readable to me.

Regarding "Audience URI (B)", this probably translates to the AudienceRestriction in SAML2. 
See http://security.stackexchange.com/q/13424/43540 and http://stackoverflow.com/a/5201647/401728
If I recall correctly the EntityID should be the metadata url, in this case “https://id.local/identity/AuthServices”.

**Comment by dahlsailrunner** [comment]
Do you want me to update the doc and do a new pull request, or will you just edit as the merge happens?  I'm happy to edit and resubmit if you like.

**Comment by albinsunnanbo** [comment]
You can just push updates to your branch and they will be included in the pull request.
The pull request is a "live" pointer to the head of your branch.
Just send a message here when you´re done.

**Comment by AndersAbel** [comment]
Thanks for the extensive documentation. This will be valuable both for those using IdentityServer3 + Okta and also for general setup of AuthServices with IdentityServer3.

You're (nearly) right in that the EntityId just have to be a prearranged value between the the Okta application and the IdentityServer. It can't be any string though, it has to be an absolute URI. The convention is to use the Url of the metadata of the SP, which in the example would be https://id.local/identity/AuthServices/.

As @albinsunnanbo noted, you can push another commit to your branch which will update the PR. However there is no built in notification in GitHub when you do so, so please add a comment here to make sure we see the change.

**Comment by dahlsailrunner** [comment]
I've updated the doc regarding the audience URI (thanks for the input and clarification on this).  Let me know if you see any other edits that should be made.

**Comment by AndersAbel** [comment]
Thanks for excellent documentation.

**Pull request merged**
