### PR TITLE
78 encrypted assertion

### PR DESCRIPTION
**Pull request by gheeres**
Implementation of issue #78.

Summary
-------------
+ Refactored certification reading into helper class. 
+ Created custom exceptions for certificate handling. 
+ Created helper / static class to decrypt an EncryptedAssertion replacing the contents of the Saml2Response with the decrypted contents.

Questions
-------------
Due to the dependency on the Windows certificate store, I'm unsure how to proceed with writing unit tests without creating an unnecessary abstraction. The previous CertificateElement class didn't handle this code coverage either... are you OK with this?

Also unsure on how to proceed with testing of message decryption. If full testing is desired, then we need a test helper able to generate EncryptedAssertion messages. Does anything exist yet?

### CODE REVIEW

**Comment by PoyaManouchehri** [comment]
@AndersAbel and @gheeres : Just some feedback regarding the issue of replacing the EncryptedAssertion XML node with an Assertion note:

I think the essence of the issue is that `Saml2Response` class has probably grown and is doing a bit too much now. Ideally there would be something like `Saml2ResponseXml` which manages the reading and writing, and then `Saml2Response` would be a logical representation that deals with Claims and metadata, and not directly with XML. Then there would then be some mapping code between the two that also deals with the encryption/decryption. There would be no need to replace the XML nodes in this case.

As a side note this code only deals with decryption, not encryption of a SAML assertion (which is fine for most use cases of this library I would imagine...)

Anyway the change I'm suggesting is probably a bigger one and outside of scope for this. I'm happy with this pull request as is (and would prefer it goes in sooner rather than later), but maybe we can create an issue for a refactor. I would be happy to contribute to that.

**Comment by AndersAbel** [comment]
@PoyaManouchehri Yes, the `Saml2Response` class does to much. One thing I'd like to move out is the XML signature stuff - and also the decryption when encrypted assertions are supported.

The reading of XML could be moved to the `SAML2PSecurityTokenHandler` class to follow the convention by the rest of `System.IdentityModel`. We just have to make sure that the `Saml2Response` class stays immutable if that is done.

I agree that those steps can be made as a separate refactoring. To get this PR merged though, I'd prefer to not replace the XML nodes when decrypting the data, but instead add them to the `allAssertionElementNodes` collection. That should be quite a small change compared to the existing PR.

**Comment by PoyaManouchehri** [comment]
Just to follow up, is anyone looking at modifying the PR? @gheeres or @AndersAbel? If not I can look into making the changes

**Comment by AndersAbel** [comment]
@PoyaManouchehri I've not had time to look at it, and I haven't heard from @gheeres for long. If you want to bring this up to date it would be appreciated.

**Comment by gheeres** [comment]
Sorry, I haven't been following this. I'm no longer using this project. We've changed our AUTH strategy to use [ADFS](https://msdn.microsoft.com/en-us/library/bb897402.aspx) which .NET WIF natively supports. ADFS is able to communicate with our SAML2 infrastructure ([Shibboleth](https://shibboleth.net/)).

**Comment by AndersAbel** [comment]
@gheeres No problem, I completely understand and am grateful for the work you've done, which I hope we'll be able to take forward and merge.

**Comment by explunit** [comment]
I made [some progress](https://github.com/explunit/authservices/tree/encrypted-assertions) on bring this PR up to date but in the end I decided that the certificate lookup code in this branch was not at the right place. The SP certificate lookup should be part of the general configuration & metadata and eventually shared with #95.

Also, the decryption approach in this branch breaks signature validation when the overall response is signed (but works OK when signature was part of the encrypted assertion itself). The spec (section 6.2) is a little vague on this point but that's how I read it.

Of course I'm willing to be corrected on any of this if I'm mistaken. I could continue this branch if we feel it's better than #273

**Comment by AndersAbel** [comment]
Closing as this is implemented by @explunit in #273.

**Pull request closed without merging**
