### PR TITLE
Encrypted assertion support

### LINKED ISSUE #78: SAML2:EncryptedAssertion support
Interfacing with [Shibboleth IDP](https://shibboleth.net/).

```xml
<saml2:EncryptedAssertion xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">
</saml2:EncryptedAssertion>
```

### PR DESCRIPTION
**Pull request by explunit**
Fixes #78 

I took an [older branch](https://github.com/Raschmann/authservices/tree/78EncryptedAssertion) by @Raschmann, rebased it on master, added configuration & metadata support, and added a few more unit tests.

I did not modify the test Idp to generate encrypted assertions, but I can tackle that in a future PR if needed.

I called the configuration property `serviceCertificate` to be consistent with what WIF calls it, and because it may also be used for signing auth requests (see #95) in the future.

### CODE REVIEW

**Comment by Raschmann** [comment]
Nice! Thank you for your contribution

**Comment by jamescrowley** [comment]
:+1: any ETA on this getting merged? We're running a custom build with this pull request in currently.

**Comment by ckouroupis** [comment]
Same here. We are also running a custom build with only this pull request. This change works great and was a necessary requirement.

**Comment by AndersAbel** [comment]
Beautiful code and long awaited functionality (and even longer wait for the merge...). Thanks @explunit!

**Pull request merged**
